In [62]:
import pandas as pd
pd.options.display.float_format = '{:.8f}'.format

In [63]:
df_live = pd.read_csv('data\live_preds.csv')
df_2019 = pd.read_csv('data/tab_tick_2019.csv')

In [57]:
tot_cols = list(df_2019.columns)
removed_cols = ['tick_avg', 'sema', 'ssma', 'lema', 'lsma', 'max_tick', 'min_tick']
remaining_cols = list(set(tot_cols) - set(removed_cols))
remaining_cols.remove('direction')
remaining_cols.sort()

In [64]:
df_2019[remaining_cols].describe()

,avg_gain,avg_loss,diff,ema_diff,lema_diff,lsma_diff,max_gap,min_gap,rs,rsi,sema_diff,sma_diff,spread_avg,ssma_diff,tick_sd
count,49950.00000000,49950.00000000,49950.00000000,49950.00000000,49950.00000000,49950.00000000,49950.00000000,49950.00000000,49950.00000000,49950.00000000,49950.00000000,49950.00000000,49950.00000000,49950.00000000,49950.00000000
mean,0.00001851,0.00001839,0.00000012,0.00000365,0.00000012,0.00000012,0.00016017,-0.00016459,402.32326997,50.16474048,0.00000012,0.00000183,0.00004046,0.00000012,0.00001995
std,0.00001286,0.00001299,0.00005495,0.00030583,0.00001623,0.00000869,0.00017772,0.00018036,20006.16538579,20.27525446,0.00001623,0.00015255,0.00005871,0.00001417,0.00001883
min,0.00000000,0.00000000,-0.00231850,-0.00316467,-0.00030479,-0.00006382,0.00000000,-0.00231525,0.00000000,0.00000000,-0.00030479,-0.00169492,0.00001350,-0.00017649,0.00000000
25%,0.00001030,0.00001020,-0.00002625,-0.00017497,-0.00000894,-0.00000496,0.00003050,-0.00023975,0.54628100,35.32870154,-0.00000894,-0.00008806,0.00002900,-0.00000800,0.00001011
50%,0.00001609,0.00001598,0.00000025,0.00000197,0.00000013,0.00000008,0.00011425,-0.00011650,1.00000000,50.00000000,0.00000013,0.00000116,0.00003350,0.00000013,0.00001612
75%,0.00002362,0.00002359,0.00002675,0.00017622,0.00000916,0.00000512,0.00023550,-0.00003250,1.85555271,64.98050985,0.00000916,0.00008814,0.00003900,0.00000806,0.00002467
max,0.00027982,0.00034562,0.00151375,0.00202183,0.00017671,0.00006660,0.00388025,0.00000000,1000000.00000000,99.99990000,0.00017671,0.00103004,0.00201000,0.00011015,0.00142160

In [65]:
df_live[remaining_cols].describe()

,avg_gain,avg_loss,diff,ema_diff,lema_diff,lsma_diff,max_gap,min_gap,rs,rsi,sema_diff,sma_diff,spread_avg,ssma_diff,tick_sd
count,283.00000000,283.00000000,283.00000000,283.00000000,283.00000000,283.00000000,283.00000000,283.00000000,283.00000000,283.00000000,283.00000000,283.00000000,283.00000000,283.00000000,283.00000000
mean,0.00003291,0.00003707,-0.00000452,-0.00005420,-0.00000493,-0.00000515,0.00033950,-0.00026914,1.43019568,46.96035330,-0.00000428,-0.00008383,0.00007465,-0.00000455,0.00003745
std,0.00001510,0.00001500,0.00008796,0.00016361,0.00001485,0.00001187,0.00027725,0.00025781,1.82263151,20.25276699,0.00002673,0.00023277,0.00000659,0.00002323,0.00001727
min,0.00000834,0.00000523,-0.00026725,-0.00041871,-0.00004797,-0.00003846,0.00000000,-0.00102900,0.15748031,13.60544218,-0.00006717,-0.00058087,0.00006050,-0.00005599,0.00000992
25%,0.00001884,0.00002573,-0.00006150,-0.00018199,-0.00001405,-0.00001090,0.00007412,-0.00044937,0.38851418,27.98045921,-0.00002517,-0.00025700,0.00007000,-0.00002362,0.00002477
50%,0.00003207,0.00003811,-0.00000525,-0.00003502,-0.00000523,-0.00000486,0.00030975,-0.00021425,0.83256997,45.43182449,-0.00000580,-0.00004709,0.00007400,-0.00000481,0.00003420
75%,0.00004464,0.00004864,0.00005988,0.00004111,0.00000498,0.00000179,0.00053663,-0.00003713,1.71568876,63.17664872,0.00001682,0.00004014,0.00007850,0.00001417,0.00004499
max,0.00007495,0.00008430,0.00022850,0.00028627,0.00003117,0.00001865,0.00115575,0.00000000,14.32423208,93.47438753,0.00006390,0.00039727,0.00009800,0.00004924,0.00010443

In [21]:
df_2019[removed_cols].describe()

,tick_avg,sema,ssma,lema,lsma,max_tick,min_tick
count,49950.000000,49950.000000,49950.000000,49950.000000,49950.000000,49950.000000,49950.000000
mean,1.141848,1.141847,1.141847,1.141843,1.141845,1.142008,1.141683
std,0.004601,0.004598,0.004597,0.004592,0.004592,0.004589,0.004610
min,1.130979,1.131352,1.131347,1.131352,1.131553,1.131633,1.130979
25%,1.138575,1.138588,1.138587,1.138588,1.138539,1.138877,1.138332
50%,1.141664,1.141640,1.141642,1.141640,1.141644,1.141820,1.141462
75%,1.145182,1.145182,1.145181,1.145182,1.145190,1.145316,1.145025
max,1.154003,1.153922,1.153909,1.153922,1.153837,1.154003,1.153803

In [22]:
df_live[removed_cols].describe()

,tick_avg,sema,ssma,lema,lsma,max_tick,min_tick
count,283.000000,283.000000,283.000000,283.000000,283.000000,283.000000,283.000000
mean,1.227698,1.227724,1.227738,1.227778,1.227821,1.228037,1.227429
std,0.000549,0.000508,0.000498,0.000440,0.000409,0.000513,0.000496
min,1.226558,1.226736,1.226728,1.226853,1.226886,1.226917,1.226558
25%,1.227217,1.227288,1.227314,1.227422,1.227494,1.227718,1.227039
50%,1.227806,1.227882,1.227900,1.227945,1.227964,1.228171,1.227587
75%,1.228108,1.228070,1.228053,1.228105,1.228155,1.228407,1.227768
max,1.228724,1.228545,1.228480,1.228369,1.228390,1.228724,1.228201