In [1]:
import numpy as np
import pandas as pd
from tqdm import tqdm
import winsound
import datetime as dt

import warnings
warnings.filterwarnings('ignore')

In [2]:
raw_df = pd.read_csv('data\M1_2019.csv')
df = raw_df[['TS', 'Close']]
print(f'{len(df)} records in df')
df.head()

372530 records in df

                 TS    Close
0  2019-01-01 17:02  1.14598
1  2019-01-01 17:03  1.14607
2  2019-01-01 17:04  1.14606
3  2019-01-01 17:05  1.14621
4  2019-01-01 17:06  1.14665

In [3]:
rsi_window = 14
window_s_ma = 10
window_l_ma = 100

In [6]:
df['diff'] = df['Close'].diff()

df['gain'] = 0
df['loss'] = 0
df['gain'].loc[df['diff'] > 0] = abs(df['diff'])
df['loss'].loc[df['diff'] < 0] = abs(df['diff'])

df['avg_gain'] = df['gain'].rolling(window=rsi_window).mean()
df['avg_loss'] = df['loss'].rolling(window=rsi_window).mean()

df['rs'] = df['avg_gain']/df['avg_loss']
df['rsi'] = 100 - (100 / (df['rs'] + 1))


df['ssma'] = df['Close'].rolling(window=window_s_ma).mean()
df['lsma'] = df['Close'].rolling(window=window_l_ma).mean()

df['sema'] = df['Close'].ewm(span=window_s_ma).mean()
df['lema'] = df['Close'].ewm(span=window_l_ma).mean()

df['target'] = df['Close'].shift(-1) - df['Close']

In [7]:
df[90:110]

,TS,Close,diff,gain,loss,avg_gain,avg_loss,rs,rsi,ssma,lsma,sema,lema,target
90,2019-01-01 18:32,1.14662,-0.00003,0.00000,0.00003,0.000018,0.000016,1.086957,52.083333,1.146653,NaN,1.146639,1.146394,-0.00002
91,2019-01-01 18:33,1.14660,-0.00002,0.00000,0.00002,0.000013,0.000018,0.720000,41.860465,1.146651,NaN,1.146632,1.146399,-0.00008
92,2019-01-01 18:34,1.14652,-0.00008,0.00000,0.00008,0.000013,0.000023,0.562500,36.000000,1.146635,NaN,1.146611,1.146402,0.00005
93,2019-01-01 18:35,1.14657,0.00005,0.00005,0.00000,0.000016,0.000020,0.821429,45.098039,1.146621,NaN,1.146604,1.146406,-0.00001
94,2019-01-01 18:36,1.14656,-0.00001,0.00000,0.00001,0.000016,0.000018,0.920000,47.916667,1.146613,NaN,1.146596,1.146410,0.00002
95,2019-01-01 18:37,1.14658,0.00002,0.00002,0.00000,0.000015,0.000018,0.840000,45.652174,1.146605,NaN,1.146593,1.146414,0.00001
96,2019-01-01 18:38,1.14659,0.00001,0.00001,0.00000,0.000011,0.000018,0.640000,39.024390,1.146597,NaN,1.146593,1.146418,0.00001
97,2019-01-01 18:39,1.14660,0.00001,0.00001,0.00000,0.000010,0.000018,0.560000,35.897436,1.146594,NaN,1.146594,1.146422,-0.00004
98,2019-01-01 18:40,1.14656,-0.00004,0.00000,0.00004,0.000010,0.000016,0.636364,38.888889,1.146585,NaN,1.146588,1.146425,-0.00003
99,2019-01-01 18:41,1.14653,-0.00003,0.00000,0.00003,0.000009,0.000018,0.480000,32.432432,1.146573,1.146312,1.146577,1.146427,-0.00001
100,2019-01-01 18:42,1.14652,-0.00001,0.00000,0.00001,0.000008,0.000019,0.423077,29.729730,1.146563,1.146317,1.146567,1.146430,-0.00005
101,2019-01-01 18:43,1.14647,-0.00005,0.00000,0.00005,0.000008,0.000019,0.407407,28.947368,1.146550,1.146321,1.146549,1.146430,0.00003
102,2019-01-01 18:44,1.14650,0.00003,0.00003,0.00000,0.000009,0.000019,0.444444,30.769231,1.146548,1.146326,1.146540,1.146432,-0.00005
103,2019-01-01 18:45,1.14645,-0.00005,0.00000,0.00005,0.000009,0.000023,0.375000,27.272727,1.146536,1.146328,1.146524,1.146432,-0.00004
104,2019-01-01 18:46,1.14641,-0.00004,0.00000,0.00004,0.000009,0.000024,0.363636,26.666667,1.146521,1.146326,1.146503,1.146432,-0.00005
105,2019-01-01 18:47,1.14636,-0.00005,0.00000,0.00005,0.000009,0.000026,0.333333,25.000000,1.146499,1.146328,1.146477,1.146430,-0.00004
106,2019-01-01 18:48,1.14632,-0.00004,0.00000,0.00004,0.000009,0.000023,0.375000,27.272727,1.146472,1.146331,1.146449,1.146428,-0.00010
107,2019-01-01 18:49,1.14622,-0.00010,0.00000,0.00010,0.000005,0.000030,0.166667,14.285714,1.146434,1.146333,1.146407,1.146423,-0.00006
108,2019-01-01 18:50,1.14616,-0.00006,0.00000,0.00006,0.000005,0.000034,0.148936,12.962963,1.146394,1.146333,1.146362,1.146417,-0.00001
109,2019-01-01 18:51,1.14615,-0.00001,0.00000,0.00001,0.000004,0.000034,0.104167,9.433962,1.146356,1.146334,1.146324,1.146411,0.00005