# ML Trader

In [1]:
from utils.packages import *
from utils.variables import *
from utils.i_o import *
from utils.dir_slope import *
from utils.engine import *
from utils.loops import *
from utils.order import *
import winsound

###  x = 2500, loss_reverse_position : 101 pips
###  x = 5000, loss_reverse_position_continous : 55 pips
###  x = 7500, loss_reverse_position_continous : -180 and -200+ pips
###  x = 1000, loss_reverse_position_continous : -170 and -170 pips

# Need to test Hedge positions with 1,2,2,2,2 (Series)

In [2]:
%%time
data = run_engine(data)

pl   -0.00645
dtype: float64

 99%|███████████████████████████████▋| 100925/102076 [00:08<00:00, 9887.32it/s]

--------------------------------------
            DateTime_frmt order_side               close_type       pl
58207 2021-01-04 14:39:09        all                all_close  0.00002
59807 2021-01-04 14:51:25        all                all_close  0.00000
64368 2021-01-04 15:17:14      short  simple_slema_move_close  0.00113
67974 2021-01-04 15:42:52      short  simple_slema_move_close  0.00004
73504 2021-01-04 16:14:05        all                all_close  0.00005
79408 2021-01-04 16:56:29        all                all_close  0.00000
81182 2021-01-04 17:10:24      short  simple_slema_move_close  0.00002
85281 2021-01-04 17:45:38        all                all_close -0.00224
86747 2021-01-04 18:00:00       long  simple_slema_move_close  0.00007
91009 2021-01-04 18:57:38      short  simple_slema_move_close  0.00022
92300 2021-01-04 19:17:04      short  simple_slema_move_close  0.00024
95500 2021-01-04 20:11:23        all                all_close  0.00001
98292 2021-01-04 21:07:23        all                all_close  0.00007
99879 2021-01-04 21:59:52        all                all_close -0.00240
99976 2021-01-04 22:05:14        all                all_close  0.00028

100%|███████████████████████████████| 102076/102076 [00:08<00:00, 12012.61it/s]

Wall time: 15.4 s

In [3]:
generate_result_report(data)

--------------------------------------
Run Complete : data/ema_df-(2021-2021)-(1-1)-(1-5).csv
--------------------------------------


--------------------------------------
Net PL
-0.0065
--------------------------------------


--------------------------------------
Monthly PL
                pl
month_val
1         -0.00645
--------------------------------------


--------------------------------------
Daily PL
               pl
date_val
4        -0.00645
--------------------------------------


--------------------------------------
Count of transactions by Close Type
..................
                         pl
close_type
all_close                12
simple_slema_move_close  16
--------------------------------------


--------------------------------------
Mean value of transactions by Close Type
..................
                               pl
close_type
all_close               -0.000793
simple_slema_move_close  0.000192
--------------------------------------


--------------------------------------
Sum by Close Type
..................
                              pl
close_type
all_close               -0.00952
simple_slema_move_close  0.00307
--------------------------------------


--------------------------------------
Average pips per day : -0.0065
--------------------------------------


--------------------------------------
Average orders per day : 28.0
--------------------------------------

In [4]:
data["plot"] = True
data['plot_type'] = 'file'
data['reduce_plot'] = True
data['plot_start']  = '2021-01-1'
data['plot_stop']   = '2021-01-5'
# data['things_to_plot'] = ['tick', 'lema', 'h_l_lema', 'tick_angle', 'positions']
data['things_to_plot'] = ['tick', 'ema', 'h_l_lema', 'tick_angle', 'positions']

In [5]:
plot_graph(data)

In [6]:
# data['df'].to_csv('data/temp.csv')

In [7]:
data['report_df']

,DateTime,Bid,Ask,Volume,i,tick,sema,lema,DateTime_frmt,tick_angle,...,all_close,close_type,pl,month_val,date_val,hour_val,long_profit,long_loss,short_profit,short_loss
5384,20210104 03:08:21.724,1.22517,1.22521,4,0,1.225190,1.225237,1.225369,2021-01-04 03:08:21,-2.530291,...,NaN,simple_slema_move_close,0.00001,1,4,3,1.22517,NaN,NaN,NaN
10367,20210104 05:11:40.446,1.22489,1.22491,1,0,1.224900,1.224794,1.224983,2021-01-04 05:11:40,-10.655540,...,NaN,simple_slema_move_close,0.00010,1,4,5,NaN,NaN,1.22491,NaN
12763,20210104 06:02:17.825,1.22535,1.22537,1,0,1.225360,1.225586,1.224921,2021-01-04 06:02:17,0.879635,...,1.225360,all_close,0.00001,1,4,6,NaN,NaN,NaN,NaN
21011,20210104 08:00:16.367,1.22653,1.22656,1,0,1.226545,1.226267,1.226338,2021-01-04 08:00:16,7.716216,...,NaN,simple_slema_move_close,0.00003,1,4,8,1.22653,NaN,NaN,NaN
24361,20210104 08:27:31.862,1.22728,1.22729,1,0,1.227285,1.226931,1.226858,2021-01-04 08:27:31,8.600528,...,NaN,simple_slema_move_close,0.00005,1,4,8,1.22728,NaN,NaN,NaN
27449,20210104 09:01:04.070,1.22805,1.22809,1,0,1.228070,1.228233,1.227920,2021-01-04 09:01:04,20.703528,...,NaN,simple_slema_move_close,0.00056,1,4,9,1.22805,NaN,NaN,NaN
31541,20210104 09:46:46.094,1.22925,1.22929,8,0,1.229270,1.229628,1.229292,2021-01-04 09:46:46,21.869590,...,NaN,simple_slema_move_close,0.00015,1,4,9,1.22925,NaN,NaN,NaN
39170,20210104 11:29:41.582,1.22968,1.22972,1,0,1.229700,1.229552,1.229487,2021-01-04 11:29:41,5.219015,...,NaN,simple_slema_move_close,0.00019,1,4,11,NaN,NaN,1.22972,NaN
41143,20210104 11:58:37.801,1.22924,1.22926,1,0,1.229250,1.229551,1.229563,2021-01-04 11:58:37,1.154985,...,NaN,simple_slema_move_close,0.00002,1,4,11,1.22924,NaN,NaN,NaN
42564,20210104 12:12:21.224,1.22921,1.22922,1,0,1.229215,1.229287,1.229346,2021-01-04 12:12:21,-7.564846,...,1.229215,all_close,0.00002,1,4,12,NaN,NaN,NaN,NaN
45538,20210104 12:52:31.876,1.22973,1.22977,6,0,1.229750,1.229653,1.229561,2021-01-04 12:52:31,6.098395,...,NaN,simple_slema_move_close,0.00004,1,4,12,NaN,NaN,1.22977,NaN
51441,20210104 13:47:24.654,1.23041,1.23044,1,0,1.230425,1.230020,1.229538,2021-01-04 13:47:24,-7.048374,...,1.230425,all_close,-0.00534,1,4,13,NaN,NaN,NaN,NaN
52786,20210104 13:59:19.950,1.22990,1.22994,10,0,1.229920,1.229687,1.229574,2021-01-04 13:59:19,4.417893,...,NaN,simple_slema_move_close,0.00020,1,4,13,NaN,NaN,1.22994,NaN
58207,20210104 14:39:09.264,1.22954,1.22957,1,0,1.229555,1.229313,1.229922,2021-01-04 14:39:09,1.437402,...,1.229555,all_close,0.00002,1,4,14,NaN,NaN,NaN,NaN
59807,20210104 14:51:25.225,1.22938,1.22940,1,0,1.229390,1.229792,1.229899,2021-01-04 14:51:25,-5.439888,...,1.229390,all_close,0.00000,1,4,14,NaN,NaN,NaN,NaN
64368,20210104 15:17:14.957,1.22795,1.22798,8,0,1.227965,1.227914,1.228248,2021-01-04 15:17:14,-22.575905,...,NaN,simple_slema_move_close,0.00113,1,4,15,NaN,NaN,1.22798,NaN
67974,20210104 15:42:52.540,1.22704,1.22706,1,0,1.227050,1.226971,1.227199,2021-01-04 15:42:52,-13.556236,...,NaN,simple_slema_move_close,0.00004,1,4,15,NaN,NaN,1.22706,NaN
73504,20210104 16:14:05.852,1.22741,1.22743,1,0,1.227420,1.227180,1.227058,2021-01-04 16:14:05,8.413931,...,1.227420,all_close,0.00005,1,4,16,NaN,NaN,NaN,NaN
79408,20210104 16:56:29.511,1.22547,1.22550,2,0,1.225485,1.225699,1.226376,2021-01-04 16:56:29,-16.881360,...,1.225485,all_close,0.00000,1,4,16,NaN,NaN,NaN,NaN
81182,20210104 17:10:24.656,1.22556,1.22559,1,0,1.225575,1.225530,1.225791,2021-01-04 17:10:24,-18.920580,...,NaN,simple_slema_move_close,0.00002,1,4,17,NaN,NaN,1.22559,NaN
85281,20210104 17:45:38.855,1.22519,1.22523,3,0,1.225210,1.225558,1.225646,2021-01-04 17:45:38,5.639525,...,1.225210,all_close,-0.00224,1,4,17,NaN,NaN,NaN,NaN
86747,20210104 18:00:00.162,1.22530,1.22531,1,0,1.225305,1.225355,1.225463,2021-01-04 18:00:00,-2.677151,...,NaN,simple_slema_move_close,0.00007,1,4,18,1.22530,NaN,NaN,NaN
91009,20210104 18:57:38.801,1.22490,1.22494,1,0,1.224920,1.224635,1.224789,2021-01-04 18:57:38,-11.333105,...,NaN,simple_slema_move_close,0.00022,1,4,18,NaN,NaN,1.22494,NaN
92300,20210104 19:17:04.892,1.22482,1.22484,1,0,1.224830,1.224700,1.224735,2021-01-04 19:17:04,-4.591292,...,NaN,simple_slema_move_close,0.00024,1,4,19,NaN,NaN,1.22484,NaN
95500,20210104 20:11:23.192,1.22474,1.22477,1,0,1.224755,1.224591,1.224834,2021-01-04 20:11:23,2.344650,...,1.224755,all_close,0.00001,1,4,20,NaN,NaN,NaN,NaN
98292,20210104 21:07:23.756,1.22462,1.22464,1,0,1.224630,1.224788,1.224621,2021-01-04 21:07:23,-6.835995,...,1.224630,all_close,0.00007,1,4,21,NaN,NaN,NaN,NaN
99879,20210104 21:59:52.210,1.22468,1.22495,1,0,1.224815,1.225128,1.224670,2021-01-04 21:59:52,2.637533,...,1.224815,all_close,-0.00240,1,4,21,NaN,NaN,NaN,NaN
99976,20210104 22:05:14.385,1.22493,1.22508,1,0,1.225005,1.225003,1.224674,2021-01-04 22:05:14,3.141789,...,1.225005,all_close,0.00028,1,4,22,NaN,NaN,NaN,NaN